package qupath.ext.wsinsight.commands;

import java.io.IOException;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Set;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Loads the WSInsight CLI schema produced by {@code wsinsight describe --output <path>}.
 * <p>
 * The schema is read from disk, never generated here: it is machine-generated by
 * the CLI itself, so regenerating or re-validating it from Java would only add a
 * second, less reliable source of truth. Keeping it on disk also means menus are
 * built without any Docker call at startup.
 */
public final class SchemaLoader {

    private static final Logger logger = LoggerFactory.getLogger(SchemaLoader.class);

    /** Default location; users regenerate it with {@code wsinsight describe --output}. */
    public static final String DEFAULT_PATH =
            System.getProperty("user.home") + "/.wsinsight/cli-schema.json";

    private final JsonObject root;

    private SchemaLoader(JsonObject root) {
        this.root = root;
    }

    /** Thrown with an actionable message when the schema is missing or malformed. */
    public static class SchemaUnavailableException extends IOException {
        public SchemaUnavailableException(String message) {
            super(message);
        }
    }

    public static SchemaLoader fromFile(Path path) throws IOException {
        if (!Files.isRegularFile(path)) {
            throw new SchemaUnavailableException(
                    "WSInsight CLI schema not found at " + path + ".\n\n"
                    + "Generate it with:\n"
                    + "    wsinsight describe --output " + path + "\n\n"
                    + "then set the path under Edit \u2192 Preferences \u2192 WSInsight.");
        }
        JsonObject parsed;
        try (Reader r = Files.newBufferedReader(path, StandardCharsets.UTF_8)) {
            parsed = new Gson().fromJson(r, JsonObject.class);
        } catch (com.google.gson.JsonParseException e) {
            throw new SchemaUnavailableException(
                    "WSInsight CLI schema at " + path + " is not valid JSON: " + e.getMessage());
        }
        if (parsed == null || !parsed.has("commands") || !parsed.get("commands").isJsonObject()) {
            throw new SchemaUnavailableException(
                    "WSInsight CLI schema at " + path + " has no 'commands' object. "
                    + "Regenerate it with: wsinsight describe --output " + path);
        }
        return new SchemaLoader(parsed);
    }

    /** wsinsight version that produced this schema, or empty when not recorded. */
    public String wsinsightVersion() {
        JsonElement v = root.get("wsinsight_version");
        return v != null && !v.isJsonNull() ? v.getAsString() : "";
    }

    /**
     * Zoo models reported by the CLI, in registry order.
     * Empty for schemas produced before models were included, in which case
     * callers fall back to a free-text model field.
     */
    public List<ModelSpec> models() {
        List<ModelSpec> out = new ArrayList<>();
        JsonElement el = root.get("models");
        if (el == null || !el.isJsonArray()) return out;
        for (JsonElement e : el.getAsJsonArray()) {
            if (!e.isJsonObject()) continue;
            JsonObject m = e.getAsJsonObject();
            String name = str(m, "name");
            if (name == null || name.isBlank()) continue;
            out.add(new ModelSpec(name, str(m, "description"), str(m, "path")));
        }
        return out;
    }

    /** One zoo model: the {@code --model} value plus a human-readable label. */
    public static final class ModelSpec {
        public final String name;
        public final String description;
        /** Absolute model folder as seen by wsinsight, or null when only on HuggingFace. */
        public final String path;

        ModelSpec(String name, String description, String path) {
            this.name = name;
            this.description = description == null ? "" : description;
            this.path = path == null || path.isBlank() ? null : path;
        }

        /** Dropdown text. The description is long, so it belongs in a tooltip. */
        public String label() {
            return name;
        }
    }

    /** Command names in the schema, sorted for stable menu order. */
    public List<String> commandNames() {
        List<String> names = new ArrayList<>();
        JsonObject cmds = root.getAsJsonObject("commands");
        if (cmds == null) return names;
        names.addAll(new TreeMap<>(cmds.asMap()).keySet());
        return names;
    }

    public String commandHelp(String name) {
        JsonObject cmd = command(name);
        if (cmd == null) return "";
        JsonElement h = cmd.get("help");
        return h != null && !h.isJsonNull() ? h.getAsString() : "";
    }

    public List<ParamSpec> specsFor(String name) {
        JsonObject cmd = command(name);
        if (cmd == null) return List.of();
        JsonArray params = cmd.getAsJsonArray("params");
        if (params == null) return List.of();
        List<ParamSpec> out = new ArrayList<>(params.size());
        for (JsonElement el : params) {
            ParamSpec s = toSpec(el.getAsJsonObject());
            if (s != null) out.add(s);
        }
        return out;
    }

    private JsonObject command(String name) {
        JsonObject cmds = root.getAsJsonObject("commands");
        return cmds == null ? null : cmds.getAsJsonObject(name);
    }

    /**
     * Flags whose CLI default (off) is overridden to on. GeoJSON is the only
     * format this extension imports, so leaving it off makes a run produce
     * nothing QuPath can display. Still a checkbox, so it can be turned off.
     */
    private static final Set<String> GEOJSON_EXPORT_FLAGS =
            Set.of("--export-geojson", "--geojson");

    private static ParamSpec toSpec(JsonObject p) {
        String kind = str(p, "kind");
        boolean isFlag = bool(p, "is_flag", false);
        boolean isOption = "option".equals(str(p, "param_type"));
        String flag = firstLongFlag(p);
        String label = deriveLabel(p, flag);
        String help = str(p, "help");
        String defaultValue = defaultAsString(p);
        if (GEOJSON_EXPORT_FLAGS.contains(flag)) {
            defaultValue = "true";
        }
        boolean required = bool(p, "required", false);

        ParamSpec.Kind specKind;
        List<String> choices = null;
        boolean translatePath = false;

        if (isFlag || "bool".equalsIgnoreCase(kind)) {
            specKind = ParamSpec.Kind.BOOL_FLAG;
        } else if ("choice".equalsIgnoreCase(kind) && p.has("choices")) {
            specKind = ParamSpec.Kind.CHOICE;
            choices = new ArrayList<>();
            for (JsonElement c : p.getAsJsonArray("choices"))
                choices.add(c.getAsString());
        } else if ("path".equalsIgnoreCase(kind)
                || isPathByName(str(p, "name"))) {
            // Either Click declared it as a path, or the option name looks
            // like a filesystem path (e.g. --wsi-dir / --results-dir, which
            // use the custom URIPath type and therefore come through the
            // schema as "string"). Treat both as PATH so the dialog renders
            // a Browse button.
            specKind = ParamSpec.Kind.PATH;
            // Paths referring to slides/results directories should be mapped
            // host↔container; locally-generated outputs outside those mounts
            // should not be. We can't know from the schema alone, so apply a
            // name-based heuristic: anything matching /wsi|dir|path|output|file/
            // is translated. The user can still override via extra mounts.
            String n = str(p, "name");
            translatePath = n != null && n.toLowerCase(Locale.ROOT)
                    .matches(".*(wsi|dir|path|output|file|manifest|registry|results|slides).*");
        } else if ("int".equalsIgnoreCase(kind)) {
            specKind = ParamSpec.Kind.INT;
        } else if ("float".equalsIgnoreCase(kind)) {
            specKind = ParamSpec.Kind.DOUBLE;
        } else {
            specKind = ParamSpec.Kind.STRING;
        }

        ParamSpec.Builder b = ParamSpec.builder()
                .flag(isOption ? flag : null)
                .label(label)
                .help(help)
                .kind(specKind)
                .defaultValue(defaultValue)
                .required(required)
                .group(str(p, "group"))
                .nargs(intOr(p, "nargs", 1))
                .columnBreak(bool(p, "column_break", false));
        if (choices != null) b.choices(choices);
        if (translatePath) b.translatePath(true);
        return b.build();
    }

    /**
     * Name-based detection of path-like options whose Click type is a custom
     * path wrapper (e.g. {@code URIPath}) and therefore reported as
     * {@code "string"} in the schema. Matches names ending in
     * {@code _dir} / {@code _path} / {@code _file} or containing
     * {@code wsi_dir} / {@code results_dir}.
     */
    private static boolean isPathByName(String name) {
        if (name == null) return false;
        String n = name.toLowerCase(Locale.ROOT);
        return n.endsWith("_dir") || n.endsWith("_path") || n.endsWith("_file")
                || n.equals("dir") || n.equals("path") || n.equals("file")
                || n.contains("wsi_dir") || n.contains("results_dir")
                || n.contains("output_dir") || n.contains("input_dir")
                || n.contains("cache_dir") || n.contains("manifest")
                || n.contains("registry");
    }

    private static String firstLongFlag(JsonObject p) {        if (!p.has("flags")) return null;
        JsonArray arr = p.getAsJsonArray("flags");
        String first = null;
        for (JsonElement el : arr) {
            String s = el.getAsString();
            if (s.startsWith("--")) return s;
            if (first == null) first = s;
        }
        return first;
    }

    private static String deriveLabel(JsonObject p, String flag) {
        String name = str(p, "name");
        if (flag != null) {
            String raw = flag.replaceFirst("^--", "").replaceFirst("^-", "");
            return prettify(raw);
        }
        return name == null ? "value" : prettify(name);
    }

    private static String prettify(String raw) {
        String s = raw.replace('_', ' ').replace('-', ' ').trim();
        return s.isEmpty() ? raw : s;
    }

    private static String defaultAsString(JsonObject p) {
        JsonElement d = p.get("default");
        if (d == null || d.isJsonNull()) return "";
        if (d.isJsonPrimitive()) {
            if (d.getAsJsonPrimitive().isBoolean())
                return Boolean.toString(d.getAsBoolean());
            return d.getAsString();
        }
        // Tuple defaults (click type=(int, int)) arrive as a JSON array; the CLI
        // wants them space-separated, not as "[2048,2048]".
        if (d.isJsonArray()) {
            StringBuilder sb = new StringBuilder();
            for (JsonElement e : d.getAsJsonArray()) {
                if (sb.length() > 0) sb.append(' ');
                sb.append(e.isJsonPrimitive() ? e.getAsString() : e.toString());
            }
            return sb.toString();
        }
        return d.toString();
    }

    private static String str(JsonObject o, String key) {
        JsonElement el = o.get(key);
        return el == null || el.isJsonNull() ? null : el.getAsString();
    }

    private static boolean bool(JsonObject o, String key, boolean def) {
        JsonElement el = o.get(key);
        return el == null || el.isJsonNull() ? def : el.getAsBoolean();
    }

    private static int intOr(JsonObject o, String key, int def) {
        JsonElement el = o.get(key);
        try {
            return el == null || el.isJsonNull() ? def : Math.max(1, el.getAsInt());
        } catch (NumberFormatException e) {
            return def;
        }
    }

    /** @return the underlying JsonObject for advanced inspection. */
    public JsonObject raw() { return root; }

    /** Stable map view of the per-command help texts. */
    public Map<String, String> commandHelps() {
        Map<String, String> out = new TreeMap<>();
        for (String n : commandNames()) out.put(n, commandHelp(n));
        return out;
    }

    // ------------------------------------------------------------------
    // Groups
    // ------------------------------------------------------------------

    /**
     * UI grouping metadata for a collection of {@link ParamSpec}s that share
     * the same {@link ParamSpec#group} key. A group can render either as a
     * sub-dialog (button on the main form that opens a modal) or inline
     * (rows appended to the main form, optionally gated by {@link #visibleWhen}).
     */
    public static final class GroupSpec {
        public enum Render { DIALOG, INLINE }

        public final String key;
        public final String title;
        public final Render render;
        /** Label shown on the button that opens the sub-dialog. Dialog groups only. */
        public final String buttonLabel;
        /** If non-null, the group (button or inline rows) is only shown when this condition holds. */
        public final ParamSpec.VisibleWhen visibleWhen;

        public GroupSpec(String key, String title, Render render,
                         String buttonLabel, ParamSpec.VisibleWhen vw) {
            this.key = key;
            this.title = title == null ? key : title;
            this.render = render == null ? Render.DIALOG : render;
            this.buttonLabel = buttonLabel;
            this.visibleWhen = vw;
        }
    }

    /**
     * @return group key → {@link GroupSpec}, in schema declaration order.
     *         Empty when the command declares no {@code groups} object.
     */
    public Map<String, GroupSpec> groupsFor(String command) {
        JsonObject cmd = command(command);
        if (cmd == null || !cmd.has("groups") || cmd.get("groups").isJsonNull())
            return Map.of();
        JsonObject groups = cmd.getAsJsonObject("groups");
        Map<String, GroupSpec> out = new LinkedHashMap<>();
        for (Map.Entry<String, JsonElement> e : groups.entrySet()) {
            if (!e.getValue().isJsonObject()) continue;
            JsonObject g = e.getValue().getAsJsonObject();
            String renderStr = str(g, "render");
            GroupSpec.Render render = "inline".equalsIgnoreCase(renderStr)
                    ? GroupSpec.Render.INLINE : GroupSpec.Render.DIALOG;
            out.put(e.getKey(), new GroupSpec(
                    e.getKey(),
                    str(g, "title"),
                    render,
                    str(g, "button_label"),
                    parseVisibleWhen(g.get("visible_when"))));
        }
        return out;
    }

    private static ParamSpec.VisibleWhen parseVisibleWhen(JsonElement el) {
        if (el == null || !el.isJsonObject()) return null;
        JsonObject o = el.getAsJsonObject();
        String flag = str(o, "flag");
        if (flag == null) return null;
        String equals = null;
        Boolean isSet = null;
        JsonElement eq = o.get("equals");
        if (eq != null && !eq.isJsonNull()) {
            if (eq.isJsonPrimitive() && eq.getAsJsonPrimitive().isBoolean())
                equals = Boolean.toString(eq.getAsBoolean());
            else
                equals = eq.getAsString();
        }
        JsonElement is = o.get("is_set");
        if (is != null && !is.isJsonNull())
            isSet = is.getAsBoolean();
        return new ParamSpec.VisibleWhen(flag, equals, isSet);
    }
}
